---
abstract: 'Easy Cache Access From Moose Objects'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  IO::Socket::INET: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-WithCache
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Cache::Memcached: 0
  Data::Dumper: 0
  Digest::MD5: 0
  Moose: 0.59
  MooseX::Role::Parameterized: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01002
